version: '3.8'

services:
  ui:
    build: ui
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app-network
  api:
    build: api
    ports:
      - "8000:8000"
    environment:
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Redis__ConnectionString=redis:6379
      - Ollama__BaseAddress=http://ollama:11434/
    depends_on:
      - redis
      - ollama
    networks:
      - app-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  ollama:
    build: llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: